# Generated by Django 5.2.7 on 2025-11-01 02:06

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('type', models.CharField(choices=[('feature', 'Feature Film'), ('short', 'Short Film'), ('documentary', 'Documentary'), ('series', 'TV Series'), ('commercial', 'Commercial'), ('music_video', 'Music Video')], default='feature', max_length=20)),
                ('status', models.CharField(choices=[('development', 'Development'), ('pre_production', 'Pre-Production'), ('production', 'Production'), ('post_production', 'Post-Production'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='development', max_length=20)),
                ('genre', models.CharField(choices=[('action', 'Action'), ('adventure', 'Adventure'), ('comedy', 'Comedy'), ('drama', 'Drama'), ('horror', 'Horror'), ('romance', 'Romance'), ('thriller', 'Thriller'), ('sci_fi', 'Science Fiction'), ('fantasy', 'Fantasy'), ('documentary', 'Documentary'), ('animation', 'Animation')], default='drama', max_length=20)),
                ('logline', models.TextField(blank=True)),
                ('budget_range', models.CharField(choices=[('micro', 'Micro ($0-50K)'), ('low', 'Low Budget ($50K-1M)'), ('medium', 'Medium Budget ($1M-20M)'), ('high', 'High Budget ($20M+)')], default='micro', max_length=20)),
                ('timeline', models.JSONField(blank=True, default=dict)),
                ('script_file_url', models.URLField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='accounts.company')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('script_analyzed', models.BooleanField(default=False)),
                ('budget_generated', models.BooleanField(default=False)),
                ('schedule_generated', models.BooleanField(default=False)),
                ('grants_scraped', models.BooleanField(default=False)),
                ('festivals_researched', models.BooleanField(default=False)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='project_status', to='projects.project')),
            ],
            options={
                'verbose_name_plural': 'Project Statuses',
            },
        ),
    ]
