# Generated by Django 5.2.7 on 2025-11-01 03:24

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='additional_locations',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='project',
            name='company_info',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='project',
            name='core_setup_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='project',
            name='currency',
            field=models.CharField(default='USD', max_length=3),
        ),
        migrations.AddField(
            model_name='project',
            name='diversity_flags',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='project',
            name='estimated_budget',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='features_enabled',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='project',
            name='genres',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='project',
            name='languages',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='project',
            name='production_location',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='project',
            name='project_stage',
            field=models.CharField(choices=[('development', 'Development'), ('pre_production', 'Pre-Production'), ('production', 'Production'), ('post_production', 'Post-Production'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='development', max_length=20),
        ),
        migrations.AddField(
            model_name='project',
            name='synopsis',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='project',
            name='team_members',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='project',
            name='themes',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='project',
            name='budget_range',
            field=models.CharField(choices=[('micro', 'Micro ($0-50K)'), ('low', 'Low Budget ($50K-250K)'), ('medium', 'Medium Budget ($250K-1M)'), ('high', 'High Budget ($1M-5M)'), ('major', 'Major Budget ($5M+)')], default='micro', max_length=20),
        ),
        migrations.AlterField(
            model_name='project',
            name='type',
            field=models.CharField(choices=[('feature', 'Feature Film'), ('short', 'Short Film'), ('documentary', 'Documentary'), ('series', 'TV Series'), ('web_series', 'Web Series'), ('commercial', 'Commercial'), ('music_video', 'Music Video')], default='feature', max_length=20),
        ),
        migrations.CreateModel(
            name='ProjectFeature',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('feature', models.CharField(choices=[('grants', 'Grant Discovery & Tracking'), ('budget', 'Budget Builder'), ('schedule', 'Production Schedule'), ('festivals', 'Festival Research & Submissions'), ('script', 'Script Analysis & Breakdown')], max_length=20)),
                ('setup_completed', models.BooleanField(default=False)),
                ('setup_data', models.JSONField(blank=True, default=dict)),
                ('last_run_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_features', to='projects.project')),
            ],
            options={
                'unique_together': {('project', 'feature')},
            },
        ),
    ]
