# Generated by Django 5.2.7 on 2025-11-01 02:06

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('create', 'Create'), ('update', 'Update'), ('delete', 'Delete'), ('upload', 'Upload'), ('generate', 'Generate'), ('submit', 'Submit')], max_length=20)),
                ('section', models.CharField(choices=[('project', 'Project'), ('script', 'Script'), ('budget', 'Budget'), ('schedule', 'Schedule'), ('grant', 'Grant'), ('festival', 'Festival')], max_length=20)),
                ('description', models.CharField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('section', models.CharField(choices=[('script', 'Script'), ('budget', 'Budget'), ('schedule', 'Schedule'), ('grant', 'Grant'), ('festival', 'Festival'), ('general', 'General')], default='general', max_length=20)),
                ('item_id', models.CharField(blank=True, max_length=100)),
                ('comment_text', models.TextField()),
                ('mentions', models.JSONField(default=list)),
                ('resolved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('comment', 'Comment'), ('mention', 'Mention'), ('project_update', 'Project Update'), ('grant_deadline', 'Grant Deadline'), ('festival_deadline', 'Festival Deadline'), ('agent_complete', 'Agent Complete')], max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('link', models.CharField(blank=True, max_length=200)),
                ('read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
