# Generated by Django 5.2.7 on 2025-11-01 02:06

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Grant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('organization', models.CharField(max_length=200)),
                ('url', models.URLField()),
                ('deadline', models.DateField()),
                ('amount_min', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('amount_max', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('grant_type', models.CharField(choices=[('development', 'Development'), ('production', 'Production'), ('post_production', 'Post Production'), ('distribution', 'Distribution'), ('general', 'General')], default='general', max_length=20)),
                ('eligibility_criteria', models.JSONField(default=dict)),
                ('application_requirements', models.JSONField(default=dict)),
                ('location_restrictions', models.JSONField(default=dict)),
                ('project_types', models.JSONField(default=list)),
                ('scraped_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source', models.CharField(default='manual', max_length=100)),
            ],
            options={
                'ordering': ['deadline'],
            },
        ),
        migrations.CreateModel(
            name='GrantMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_score', models.IntegerField(default=0)),
                ('match_reasoning', models.TextField()),
                ('status', models.CharField(choices=[('suggested', 'Suggested'), ('applied', 'Applied'), ('awarded', 'Awarded'), ('rejected', 'Rejected')], default='suggested', max_length=20)),
                ('applied_at', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('grant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='grants.grant')),
            ],
            options={
                'ordering': ['-match_score', 'grant__deadline'],
            },
        ),
    ]
