# Generated by Django 5.2.7 on 2025-11-01 02:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('grants', '0001_initial'),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='grantmatch',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grant_matches', to='projects.project'),
        ),
        migrations.AlterUniqueTogether(
            name='grantmatch',
            unique_together={('project', 'grant')},
        ),
    ]
