# Generated by Django 5.2.7 on 2025-11-01 03:24

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grants', '0002_initial'),
        ('projects', '0002_project_additional_locations_project_company_info_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='grant',
            name='annual_cycle',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='grant',
            name='application_process',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='grant',
            name='contact_info',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='grant',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='grant',
            name='funding_type',
            field=models.CharField(choices=[('grant', 'Grant'), ('tax_credit', 'Tax Credit'), ('rebate', 'Rebate'), ('loan', 'Loan'), ('equity', 'Equity'), ('mixed', 'Mixed')], default='grant', max_length=20),
        ),
        migrations.AddField(
            model_name='grant',
            name='matched_projects_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='grant',
            name='selection_criteria',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='grant',
            name='success_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='grant',
            name='tags',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='grantmatch',
            name='application_documents',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='grantmatch',
            name='application_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='grantmatch',
            name='deadline_reminder_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='grantmatch',
            name='follow_up_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='grantmatch',
            name='match_details',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='grantmatch',
            name='match_quality',
            field=models.CharField(blank=True, choices=[('perfect', 'Perfect Match (90-100%)'), ('excellent', 'Excellent Match (80-89%)'), ('good', 'Good Match (70-79%)'), ('fair', 'Fair Match (60-69%)'), ('poor', 'Poor Match (50-59%)')], max_length=20),
        ),
        migrations.AddField(
            model_name='grantmatch',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='grantmatch',
            name='status',
            field=models.CharField(choices=[('suggested', 'Suggested'), ('interested', 'Interested'), ('applied', 'Applied'), ('under_review', 'Under Review'), ('awarded', 'Awarded'), ('rejected', 'Rejected'), ('withdrawn', 'Withdrawn')], default='suggested', max_length=20),
        ),
        migrations.CreateModel(
            name='GrantApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_id', models.CharField(blank=True, max_length=100)),
                ('submission_date', models.DateTimeField(blank=True, null=True)),
                ('confirmation_number', models.CharField(blank=True, max_length=100)),
                ('requirements_checklist', models.JSONField(blank=True, default=list)),
                ('completed_requirements', models.JSONField(blank=True, default=list)),
                ('completion_percentage', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5)),
                ('submitted_documents', models.JSONField(blank=True, default=dict)),
                ('additional_materials', models.JSONField(blank=True, default=list)),
                ('communication_log', models.JSONField(blank=True, default=list)),
                ('decision_date', models.DateField(blank=True, null=True)),
                ('award_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('feedback_received', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('grant_match', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='application', to='grants.grantmatch')),
            ],
        ),
        migrations.CreateModel(
            name='GrantPreferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preferred_funding_types', models.JSONField(blank=True, default=list)),
                ('funding_priorities', models.JSONField(blank=True, default=list)),
                ('min_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('max_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('preferred_regions', models.JSONField(blank=True, default=list)),
                ('excluded_regions', models.JSONField(blank=True, default=list)),
                ('max_application_complexity', models.IntegerField(default=5)),
                ('lead_time_preference', models.IntegerField(default=30)),
                ('recurring_grants_only', models.BooleanField(default=False)),
                ('genre_requirements', models.JSONField(blank=True, default=list)),
                ('theme_requirements', models.JSONField(blank=True, default=list)),
                ('diversity_requirements', models.JSONField(blank=True, default=list)),
                ('company_age_minimum', models.IntegerField(blank=True, null=True)),
                ('track_record_required', models.BooleanField(default=False)),
                ('collaboration_required', models.BooleanField(default=False)),
                ('auto_apply_enabled', models.BooleanField(default=False)),
                ('auto_apply_threshold', models.IntegerField(default=80)),
                ('notification_preferences', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='grant_preferences', to='projects.project')),
            ],
        ),
    ]
