# Generated by Django 5.2.7 on 2025-11-01 02:06

import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('meta', models.JSONField(blank=True, default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('type', models.CharField(choices=[('studio', 'Studio'), ('practical', 'Practical Location'), ('outdoor', 'Outdoor'), ('green_screen', 'Green Screen')], default='practical', max_length=20)),
                ('meta', models.JSONField(blank=True, default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='Scene',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('number', models.IntegerField()),
                ('slug', models.CharField(max_length=100)),
                ('header', models.CharField(max_length=200)),
                ('int_ext', models.CharField(choices=[('INT', 'Interior'), ('EXT', 'Exterior')], max_length=3)),
                ('day_night', models.CharField(choices=[('DAY', 'Day'), ('NIGHT', 'Night'), ('DAWN', 'Dawn'), ('DUSK', 'Dusk')], max_length=5)),
                ('location', models.CharField(max_length=200)),
                ('characters', models.JSONField(default=list)),
                ('est_shoot_hours', models.DecimalField(decimal_places=2, default=Decimal('1.0'), max_digits=4)),
                ('complexity', models.CharField(choices=[('simple', 'Simple'), ('medium', 'Medium'), ('complex', 'Complex'), ('very_complex', 'Very Complex')], default='simple', max_length=20)),
                ('special', models.JSONField(blank=True, default=dict)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['number'],
            },
        ),
        migrations.CreateModel(
            name='ScriptBreakdown',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
