# Generated by Django 5.2.7 on 2025-11-01 02:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('breakdown', '0001_initial'),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scriptbreakdown',
            name='project',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='breakdown', to='projects.project'),
        ),
        migrations.AddField(
            model_name='scene',
            name='breakdown',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scenes', to='breakdown.scriptbreakdown'),
        ),
        migrations.AddField(
            model_name='location',
            name='breakdown',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='breakdown.scriptbreakdown'),
        ),
        migrations.AddField(
            model_name='character',
            name='breakdown',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='characters', to='breakdown.scriptbreakdown'),
        ),
        migrations.AlterUniqueTogether(
            name='scene',
            unique_together={('breakdown', 'number')},
        ),
        migrations.AlterUniqueTogether(
            name='location',
            unique_together={('breakdown', 'name')},
        ),
        migrations.AlterUniqueTogether(
            name='character',
            unique_together={('breakdown', 'name')},
        ),
    ]
