# Generated by Django 5.2.7 on 2025-11-01 02:06

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version', models.IntegerField(default=1)),
                ('total_days', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('approved', 'Approved'), ('locked', 'Locked')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='projects.project')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('project', 'version')},
            },
        ),
        migrations.CreateModel(
            name='ShootDay',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('day_number', models.IntegerField()),
                ('date', models.DateField(blank=True, null=True)),
                ('location', models.CharField(max_length=200)),
                ('scenes', models.JSONField(default=list)),
                ('call_time', models.TimeField(blank=True, null=True)),
                ('wrap_time', models.TimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('order_index', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shoot_days', to='schedules.schedule')),
            ],
            options={
                'ordering': ['order_index', 'day_number'],
                'unique_together': {('schedule', 'day_number')},
            },
        ),
    ]
