# Generated by Django 5.2.7 on 2025-11-01 02:06

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Festival',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=200)),
                ('website_url', models.URLField()),
                ('submission_url', models.URLField(blank=True)),
                ('dates', models.JSONField(default=dict)),
                ('deadline_early', models.DateField(blank=True, null=True)),
                ('deadline_regular', models.DateField(blank=True, null=True)),
                ('deadline_late', models.DateField(blank=True, null=True)),
                ('fee_early', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('fee_regular', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('fee_late', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('tier', models.CharField(choices=[('a_list', 'A-List'), ('regional', 'Regional'), ('genre', 'Genre-Specific'), ('online', 'Online'), ('student', 'Student')], default='regional', max_length=20)),
                ('genres', models.JSONField(default=list)),
                ('eligibility_criteria', models.JSONField(default=dict)),
                ('awards', models.JSONField(default=list)),
                ('prestige_score', models.IntegerField(default=50)),
                ('scraped_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-prestige_score', 'deadline_regular'],
            },
        ),
        migrations.CreateModel(
            name='FestivalMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_score', models.IntegerField(default=0)),
                ('strategy_notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('considering', 'Considering'), ('submitted', 'Submitted'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='considering', max_length=20)),
                ('submitted_at', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('festival', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='festivals.festival')),
            ],
            options={
                'ordering': ['-match_score', 'festival__deadline_regular'],
            },
        ),
    ]
